version: "3.8"

services:
  service:
    build: 
      context: ./service
    container_name: lone_checker_service
    env_file:
      - ./service/.env
    expose:
      - "3000"
    restart: unless-stopped
  
  nginx:
    image: nginx:alpine
    container_name: lone_checker_nginx
    ports:
      - "90:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - service
    restart: unless-stopped

